/**
 * Midnight provider wiring for the DisputeVault gateway
 * (docs/ARCHITECTURE.md §2 `gateway/src/chain.ts`).
 *
 * This module is the ONLY place in the repository that touches Midnight
 * network tooling (docs/ARCHITECTURE.md §3.2/§3.3). Everything here follows
 * the pinned repository toolchain (README "Toolchain"):
 *
 *   - @midnight-ntwrk/midnight-js 4.1.1   provider contracts + deploy/call
 *   - @midnight-ntwrk/testkit-js 4.1.1    official server-side wallet:
 *       MidnightWalletProvider implements midnight-js's WalletProvider AND
 *       MidnightProvider over a WalletFacade (balance -> sign -> finalize,
 *       submit); initializeMidnightProviders assembles the full
 *       MidnightProviders set (Level private state, indexer public data,
 *       NodeZkConfigProvider + HTTP proof server, wallet providers).
 *   - @midnight-ntwrk/compact-runtime 0.16.0 (pulled by the compiled contract)
 *
 * This mirrors the official server-side example (midnightntwrk/example-bboard
 * `bboard-cli`), which is pinned to exactly midnight-js 4.1.1 + testkit-js
 * 4.1.1: build a MidnightWalletProvider from an EnvironmentConfiguration,
 * assemble providers with initializeMidnightProviders, then join the
 * deployed contract with findDeployedContract and a CompiledContract built
 * via CompiledContract.make(...).withWitnesses(...).withCompiledFileAssets(...).
 *
 * Secrets flow: WALLET_SEED / ADMIN_SECRET are read from the environment
 * (config.ts) into memory only. They are never logged, never returned by any
 * HTTP handler, and never written to disk by this module.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  MidnightWalletProvider,
  initializeMidnightProviders,
  type EnvironmentConfiguration,
} from '@midnight-ntwrk/testkit-js';
import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import {
  findDeployedContract,
  type FoundContract,
} from '@midnight-ntwrk/midnight-js-contracts';
import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';
import type { ContractAddress } from '@midnight-ntwrk/midnight-js-protocol/compact-runtime';
import { toHex, assertIsContractAddress } from '@midnight-ntwrk/midnight-js-utils';
import type { Logger } from 'pino';

// The compiled DisputeVault contract generated by compactc 0.31.1
// (runtime 0.16.0). Its `Contract` class exposes witnesses /
// provableCircuits / initialState — the shape compact-js's Contract
// interface expects, so midnight-js can wrap it with CompiledContract.make.
import {
  Contract as DisputeVaultGenerated,
  ledger as contractLedger,
  type Ledger,
  type Dispute,
  type DisputeStatus,
} from '../../contract/src/managed/disputevault/contract/index.js';

export { contractLedger };
export type { Ledger, Dispute, DisputeStatus };

/** Circuit identifiers of the DisputeVault contract. */
export type CircuitId = 'register_platform' | 'submit_dispute' | 'post_verdict';
export const CIRCUIT_IDS: readonly CircuitId[] = [
  'register_platform',
  'submit_dispute',
  'post_verdict',
];

/**
 * DisputeVault has no application private state: the admin secret arrives
 * via the `adminSecret()` witness, not via stored private state.
 */
export type DisputeVaultPrivateState = null;

/**
 * Contract type as seen by midnight-js (compact-js Contract interface).
 * DisputeVault has no application private state (the admin secret arrives
 * via the adminSecret() witness), so the private-state parameter is null.
 */
export type DisputeVaultCompactContract = DisputeVaultGenerated<null>;

/** The compiled-contract binding handed to midnight-js. */
export type DisputeVaultCompiledContract = ReturnType<
  typeof makeCompiledContract
>;

/**
 * Build the CompiledContract binding for DisputeVault with the given admin
 * secret as the `adminSecret()` witness (PROTOCOL.md §9: the secret is a
 * private witness; adminPk(sk) is derived and compared in-circuit against
 * the constructor-bound admin_authority).
 *
 * The witness closes over the in-memory secret ONLY — it is never persisted
 * and never exposed through any other path.
 */
export function makeCompiledContract(
  adminSecret: Uint8Array,
): CompiledContract.CompiledContract<
  Contract.DisputeVaultEffectContract,
  DisputeVaultPrivateState
> {
  return CompiledContract.make<DisputeVaultCompactContract>(
    'disputevault',
    DisputeVaultGenerated,
  ).pipe(
    CompiledContract.withWitnesses({
      adminSecret: (
        context: import('@midnight-ntwrk/compact-runtime').WitnessContext<Ledger, DisputeVaultPrivateState>,
      ): [DisputeVaultPrivateState, Uint8Array] => {
        void context;
        return [null, adminSecret];
      },
    }),
    CompiledContract.withCompiledFileAssets(zkAssetsPath()),
  ) as never;
}

/** Where compactc wrote the ZK assets (zkir/, keys/). */
export function zkAssetsPath(): string {
  // gateway/src/chain.ts -> repo root -> contract/src/managed/disputevault
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, '../../contract/src/managed/disputevault');
}

/** Runtime handles for the connected contract. */
export interface ChainConnection {
  /** Full midnight-js provider set (from initializeMidnightProviders). */
  readonly providers: ReturnType<typeof initializeMidnightProviders>;
  /** The found deployed contract (callTx interface per circuit). */
  readonly deployed: FoundContract<never>;
  readonly contractAddress: ContractAddress;
  /** Coin public key of the gateway wallet (safe to expose). */
  readonly coinPublicKey: string;
  /** Disengage the wallet + providers on shutdown. */
  readonly close: () => Promise<void>;
}

/** Options for {@link connectContract}. */
export interface ConnectOptions {
  /** midnight-js network id string ('undeployed' | 'preview' | 'preprod'). */
  readonly network: string;
  readonly indexerUrl: string;
  readonly indexerWsUrl: string;
  readonly proofServerUrl: string;
  readonly nodeUrl: string;
  readonly nodeWsUrl: string;
  /** BIP32 master seed (hex) for the gateway wallet. */
  readonly walletSeed: string;
  /** 32-byte admin secret (the adminSecret witness). */
  readonly adminSecret: Uint8Array;
  /** Directory holding compiled ZK artifacts (zkir/, keys/ subdirs). */
  readonly zkAssetsDir: string;
  readonly contractAddress: string;
  /** State directory for the private-state LevelDB store. */
  readonly privateStateDir: string;
  readonly logger: Logger;
}

/** Check that the compiled ZK artifact directories exist. */
export function assertZkAssetsPresent(zkAssetsDir: string): void {
  const zkir = path.join(zkAssetsDir, 'zkir');
  const keys = path.join(zkAssetsDir, 'keys');
  for (const dir of [zkir, keys]) {
    if (!fs.existsSync(dir)) {
      throw new Error(
        `compiled ZK assets not found at ${dir} - compile the contract first (cd contract && npm run compact)`,
      );
    }
  }
}

/** wallet-sdk NetworkId accepted strings, matching config's MidnightNetwork. */
export const WALLET_NETWORK_IDS = ['undeployed', 'preview', 'preprod'] as const;

/**
 * Wire the concrete provider set against a real Midnight deployment and bind
 * the deployed DisputeVault contract. Performs no transaction: connectivity
 * is verified lazily by the first read/write, and /health reports connection
 * state without secrets.
 */
export async function connectContract(
  opts: ConnectOptions,
): Promise<ChainConnection> {
  assertZkAssetsPresent(opts.zkAssetsDir);

  // midnight-js global network id (affects address/tx encoding).
  setNetworkId(opts.network);

  const env: EnvironmentConfiguration = {
    walletNetworkId: opts.network as EnvironmentConfiguration['walletNetworkId'],
    networkId: opts.network,
    indexer: opts.indexerUrl,
    indexerWS: opts.indexerWsUrl,
    node: opts.nodeUrl,
    nodeWS: opts.nodeWsUrl,
    proofServer: opts.proofServerUrl,
    faucet: undefined,
  };

  const walletProvider = await MidnightWalletProvider.build(
    opts.logger,
    env,
    opts.walletSeed,
  );

  const providers = initializeMidnightProviders(walletProvider, env, {
    privateStateStoreName: path.join(
      opts.privateStateDir,
      'disputevault-gateway-private-state',
    ),
    zkConfigPath: opts.zkAssetsDir,
  });

  assertIsContractAddress(opts.contractAddress);
  const contractAddress = opts.contractAddress as ContractAddress;

  const compiled = makeCompiledContract(opts.adminSecret);
  const deployed = await findDeployedContract(providers as never, {
    compiledContract: compiled as never,
    contractAddress: contractAddress as never,
  } as never);

  return {
    providers: providers as ReturnType<typeof initializeMidnightProviders>,
    deployed: deployed as unknown as FoundContract<never>,
    contractAddress,
    coinPublicKey: toHex(walletProvider.getCoinPublicKey() as unknown as Uint8Array),
    close: () => walletProvider.stop(),
  };
}

/**
 * Human-readable view of the connection for /health (no secrets).
 */
export function connectionStatus(connection: ChainConnection | undefined): {
  connected: boolean;
  contractAddress: string | null;
  coinPublicKey: string | null;
} {
  if (!connection) {
    return { connected: false, contractAddress: null, coinPublicKey: null };
  }
  return {
    connected: true,
    contractAddress: toHex(connection.contractAddress as unknown as Uint8Array),
    coinPublicKey: connection.coinPublicKey,
  };
}

// Type-level helper alias used above; kept in one place so the generic
// parameter of CompiledContract.make stays readable.
declare namespace Contract {
  type DisputeVaultEffectContract = DisputeVaultCompactContract;
}
